include:
  - project: devops/gitlab-ci-base
    file: /publish-docker.yml
  - project: devops/gitlab-ci-base
    file: /push-helm-charts.yml
  - project: devops/gitlab-ci-base
    file: /shared-helmfile.yml
  - project: devops/gitlab-ci-base
    file: /deploy-helmfile.yml
  - project: devops/gitlab-ci-base
    file: /sign-image.yml
  - project: devops/gitlab-ci-base
    file: /codequality.yml
  - build-docker.yml

stages:
  - code-quality
  - build
  - push

# Проверка качества кода через sonarqube
code-quality:
  extends: .codequality
  stage: code-quality
  when: manual
  allow_failure: true

# Сборка временного артефакта
build:
  extends: .build_docker_image_maven
  stage: build
  variables:
    KANIKO_DESTINATION: >
      $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
    KANIKO_EXTRA: --no-push
    ARTIFACT_VERSION: ${CI_COMMIT_REF_SLUG}-SNAPSHOT
  only:
    changes:
      - src/**/*
      - pom.xml
      - Dockerfile
  coverage: /Total.*?([0-9]{1,3})%/

# Сборка артефакта для стенда разработки (DEV) с master ветки
push_dev:
  extends: .build_docker_image_maven
  stage: push
  variables:
    KANIKO_DESTINATION: >
      $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_REF_SLUG}
      $CI_REGISTRY/$CI_PROJECT_PATH:latest
      $CI_REGISTRY/$CI_PROJECT_PATH:dev
    ARTIFACT_VERSION: ${CI_COMMIT_REF_SLUG}-SNAPSHOT
  only:
    refs:
      - master
    changes:
      - src/**/*
      - pom.xml
      - Dockerfile
  except:
    - tags
  coverage: /Total.*?([0-9]{1,3})%/

# Сборка артефакта для стенда пре-продакшн (RC) с pre-production ветки
push_rc:
  extends: .build_docker_image_maven
  stage: push
  variables:
    KANIKO_DESTINATION: >
      $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_TAG}
      $CI_REGISTRY/$CI_PROJECT_PATH:latest
      $CI_REGISTRY/$CI_PROJECT_PATH:rc
    ARTIFACT_VERSION: ${CI_COMMIT_TAG}
  only:
    refs:
      - /^\d+\.\d+\.\d+-RC\d+$/
  except:
    - branches
    - master
  coverage: /Total.*?([0-9]{1,3})%/

# Сборка release артефакта, разворачивается на продакшн стенде (PROD) с production ветки
push_release:
  extends: .build_docker_image_maven
  stage: build
  variables:
    KANIKO_AUTHS: >
      /$CI_REGISTRY/$REGISTRY_PUSHER_LOGIN/$REGISTRY_PUSHER_PASSWORD/
      /$CI_REGISTRY_EXT/$REGISTRY_PUSHER_LOGIN/$REGISTRY_PUSHER_PASSWORD/
      /$CI_CACHE_REGISTRY/$REGISTRY_PUSHER_LOGIN/$REGISTRY_PUSHER_PASSWORD/
    KANIKO_DESTINATION: >
      $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_TAG}
      $CI_REGISTRY/$CI_PROJECT_PATH:stable
      $CI_REGISTRY/$CI_PROJECT_PATH:latest
      $CI_REGISTRY_EXT/$CI_PROJECT_PATH:latest
      $CI_REGISTRY_EXT/$CI_PROJECT_PATH:${CI_COMMIT_TAG}
    ARTIFACT_VERSION: ${CI_COMMIT_TAG}
  only:
    refs:
      - /^\d+\.\d+\.\d+$/
  except:
    - branches
    - master
  coverage: /Total.*?([0-9]{1,3})%/
